spring:
   datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
   typeAliasesPackage: com.sc.eurekauserclient.pojo
   mapperLocations: classpath:mapper/*.xml

myValue: 666