server:
  port: 3000

spring:
  application:
    name: spring-cloud-portal

eureka:
  instance:
    instance-id: spring-cloud-portal
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://admin:123@127.0.0.1:1234/eureka/
